In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('CropData.csv')

In [3]:
df

District        Village    pH     EC    OC      N       P       K  \
0        Shirala       Ambewadi  6.70  0.240  0.67  262.4   30.00  224.40   
1        Shirala       Ambewadi  6.70  0.240  0.67  262.4   30.00  224.40   
2        Shirala       Ambewadi  6.70  0.240  0.67  262.4   30.00  224.40   
3        Shirala       Ambewadi  6.70  0.240  0.67  262.4   30.00  224.40   
4        Shirala       Ambewadi  6.70  0.240  0.67  262.4   30.00  224.40   
...          ...            ...   ...    ...   ...    ...     ...     ...   
172075  Khamgaon   Chikhali Bk.  8.48  0.290  0.35  205.0    8.71  532.00   
172076  Khamgaon  Pimpri  Gawli  7.17  0.150  0.42  176.0  140.00  372.00   
172077     Dhule        Hendrun  7.80  0.611  0.24  250.0    9.14  388.00   
172078   Shirala        Shirala  7.76  0.130  0.57  225.7   27.70  324.80   
172079   Buldana          Irala  7.70  0.120  0.51  237.2    9.61  245.24   

            S    Zn    Fe    Cu     Mn     B         Soil_type  \
0       10.90  0.74  5.60  1.77   5.51  0.77           Neutral   
1       10.90  0.74  5.60  1.77   5.51  0.77           Neutral   
2       10.90  0.74  5.60  1.77   5.51  0.77           Neutral   
3       10.90  0.74  5.60  1.77   5.51  0.77           Neutral   
4       10.90  0.74  5.60  1.77   5.51  0.77           Neutral   
...       ...   ...   ...   ...    ...   ...               ...   
172075  11.55  0.41  3.49  0.58  15.38  0.73  Slighty alkaline   
172076  12.00  0.93  8.25  2.90  13.56  0.99           Neutral   
172077  20.46  0.65  5.53  2.96  13.40  1.16           Neutral   
172078  14.70  0.35  3.70  1.47   5.57  0.44           Neutral   
172079   5.33  0.45  5.29  0.49   2.74  0.57           Neutral   

          Soil_Quality       Crop  
0         Fertile Soil  GroundNut  
1         Fertile Soil  GroundNut  
2         Fertile Soil  GroundNut  
3         Fertile Soil  GroundNut  
4         Fertile Soil  GroundNut  
...                ...        ...  
172075  Unfertile Soil    No Crop  
172076  Unfertile Soil    No Crop  
172077  Unfertile Soil    No Crop  
172078    Fertile Soil    No Crop  
172079  Unfertile Soil    No Crop  

[172080 rows x 17 columns]

In [4]:
df1=df.copy() 
s=df1[df1.Crop == 'Sugarcane' ] 
s=s.sample(frac=0.18,random_state=2021)
c=df1[df1.Crop == 'Cotton' ] 
c=c.sample(frac=0.033,random_state=2021)
g=df1[df1.Crop == 'GroundNut' ] 
g=g.sample(frac=0.49,random_state=2021)
so=df1[df1.Crop == 'Soybean' ] 
so=so.sample(frac=0.077,random_state=2021)
n=df1[df1.Crop == 'No Crop' ] 
n=n.sample(frac=0.095,random_state=2021)
w=df1[df1.Crop == 'Wheat' ]
df=pd.concat([c,s,so,g,w,n])
df.shape

(16127, 17)

In [5]:
x=df.iloc[:,2:14]
y=df.iloc[:,16]

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y,test_size = 0.3,random_state=2021,stratify=y)

In [10]:
from sklearn.ensemble import RandomForestClassifier
rm=RandomForestClassifier(max_features=2,random_state=2021)
rm.fit(X_train,y_train)
predx=rm.predict(X_test)

In [11]:
ypred=rm.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
result=confusion_matrix(y_test,predx)
print("confusion matrix\n",result)
result1=classification_report(y_test,predx)
print("Classification report\n",result1)
result2=accuracy_score(y_test,predx)
print("Accuracy_score\n",result2)

confusion matrix
 [[763   3  22  40  19   8]
 [  4 790   0   0   2   0]
 [ 31   7 690  63  23   2]
 [ 29  11  46 693  11   5]
 [ 16  13   2   7 755   2]
 [  0   0   8   4   2 768]]
Classification report
               precision    recall  f1-score   support

      Cotton       0.91      0.89      0.90       855
   GroundNut       0.96      0.99      0.98       796
     No Crop       0.90      0.85      0.87       816
     Soybean       0.86      0.87      0.87       795
   Sugarcane       0.93      0.95      0.94       795
       Wheat       0.98      0.98      0.98       782

    accuracy                           0.92      4839
   macro avg       0.92      0.92      0.92      4839
weighted avg       0.92      0.92      0.92      4839

Accuracy_score
 0.9214713783839636


In [12]:
import pickle

In [ ]:
pickle_out = open("classifier.pkl","wb")
pickle.dump(rm,pickle_out)
pickle_out.close()

In [13]:
X_test

pH     EC     OC        N       P       K      S     Zn    Fe  \
99937   7.150  0.090  0.680  200.700   44.56  214.82  5.509  1.210  7.00   
5401    6.900  0.143  0.600  282.240   52.76  362.88  9.240  0.490  4.49   
118451  8.171  0.716  0.915  409.920  143.00  411.80  6.900  0.314  4.15   
121586  6.890  0.182  0.690  264.400   93.77  426.18  7.035  0.880  7.68   
57095   7.700  0.380  0.669  213.250   48.59  181.44  0.617  1.049  4.29   
...       ...    ...    ...      ...     ...     ...    ...    ...   ...   
837     7.520  0.150  0.550  225.700  124.00  337.40  4.490  0.390  4.50   
90032   7.400  0.390  0.750  525.000   17.25  454.15  8.050  0.270  2.58   
115529  6.920  0.040  0.560  335.622  110.00  255.00  0.040  0.190  0.39   
164674  7.800  0.190  0.540  357.680    7.88  469.57  1.560  0.300  1.10   
143197  6.990  0.470  0.550  357.500  132.00  563.99  2.470  0.600  0.39   

           Cu     Mn      B  
99937   0.668  17.59  0.110  
5401    3.200   5.80  0.490  
118451  0.349   1.23  0.957  
121586  2.180  10.99  1.100  
57095   0.517   9.00  1.090  
...       ...    ...    ...  
837     2.000   7.50  0.430  
90032   1.520  10.22  0.760  
115529  0.650   1.64  0.030  
164674  0.680   4.08  0.620  
143197  0.500   1.27  0.198  

[4839 rows x 12 columns]

In [16]:
#rm.predict([[7.48,0.199,0.58,234.08,16.71,164.50,6.3,1.29,4.27,2.4,13.76,1.04]])
rm.predict([[6.70,0.240,0.67,262.4,30.00,224.40,10.90,0.74,5.60,1.77,5.51,0.77]])


array(['GroundNut'], dtype=object)